# vim: set ft=yaml ts=2 sw=2 et :
name: CMake

"on":
  - push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install build deps
        run: |-
          sudo apt update
          sudo apt -y install devscripts equivs
          yes | sudo mk-build-deps -i || true

      - name: Configure CMake
        run: >-
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: >-
          cmake
          --build ${{github.workspace}}/build
          --config ${{env.BUILD_TYPE}}

